site_name: Mercator
site_url: https://dbarzin.githubs.io/mercator/
nav:
    - Introduction: index.md
    - Cartographie: cartography.md
    - Application: application.md
    - Cas d'utilisation: usecases.md
    - Modèle de données: model.md
    - Rapports: reports.md
    - Administration: admin.md
    - API: api.md
    - Références: references.md

theme: readthedocs
