docs_dir: docs

# Project information
site_name: Mercator
site_description: Mapping the Information System !

# Repository
repo_url: https://github.com/dbarzin/mercator
edit_uri: edit/master/docs

# Copyright
copyright: Copyright <a href="https://www.gnu.org/licenses/licenses.en.html">GPL</a>.

site_url: https://dbarzin.githubs.io/mercator/

theme:
  name: readthedocs

plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
          nav_translations:
            Introduction: "Introduction"
            Mapping: "Mapping"
            Application: "Application"
            BPMN 2.0: "BPMN 2.0"
            Reports: "Reports"
            Use cases: "Use cases"
            Data model: "Data model"
            Exploration: "Exploration"
            Administration: "Administration"
            Configuration: "Configuration"
            Import: "Import"
            API: "API"
            API advanced (filters): "API advanced (filters)"
            References: "References"
        - locale: fr
          name: Français
          build: true
          nav_translations:
            Introduction: "Introduction"
            Mapping: "Cartographie"
            Application: "Application"
            BPMN 2.0: "BPMN 2.0"
            Reports: "Rapports"
            Use cases: "Cas d'usage"
            Data model: "Modèle de données"
            Exploration: "Exploration"
            Administration: "Administration"
            Configuration: "Configuration"
            Import: "Import"
            API: "API"
            API advanced (filters): "API avancée (filtres)"
            References: "Références"

nav:
  - Introduction: index.md
  - Mapping: cartography.md
  - Application: application.md
  - BPMN 2.0: bpmn.md
  - Reports: reports.md
  - Use cases: usecases.md
  - Data model: model.md
  - Exploration: exploration.md
  - Administration: admin.md
  - Configuration: config.md
  - Import: import.md
  - API: api.md
  - API advanced (filters): apifilters.md
  - References: references.md

extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: Français
      link: /fr/
      lang: fr