docs_dir: docs

# Project information
site_name: Mercator
site_description: Mapping the Information System !

# Repository
repo_url: https://github.com/dbarzin/mercator
edit_uri: edit/master/docs

# Copyright
copyright: Copyright <a href="https://www.gnu.org/licenses/licenses.en.html">GPL</a>.

site_url: https://dbarzin.githubs.io/mercator/

theme:
  name: readthedocs

plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
          nav_translations:
            section title: "Section"
            subsection: "Subsection"
            page title: "Page with title translated"
        - locale: fr
          name: Français
          build: true
          nav_translations:
            section title: "Section"
            subsection: "Sous-section"
            page title: "Titre"

nav:
  - Introduction: index.md
  - Mapping: cartography.md
  - Application: application.md
  - BPMN 2.0: bpmn.md
  - Reports: reports.md
  - Use cases: usecases.md
  - Data model: model.md
  - Exploration: exploration.md
  - Administration: admin.md
  - Configuration: config.md
  - Import: import.md
  - API: api.md
  - API advanced (filters): apifilters.md
  - References: references.md

extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: Français
      link: /fr/
      lang: fr
