services:
  mercator-db:
    image: mariadb:11
    restart: unless-stopped
    container_name: mercator-db
    networks:
      - nextcloud_web
    environment:
      MYSQL_ROOT_PASSWORD: MercatorRoot123
      MYSQL_DATABASE: mercator
      MYSQL_USER: mercator
      MYSQL_PASSWORD: MercatorPass123
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - mercator_db_data:/var/lib/mysql

  mercator-app:
    image: ghcr.io/dbarzin/mercator:latest
    restart: unless-stopped
    container_name: mercator-app
    volumes:
      - ./docs:/var/www/mercator/storage/docs
    expose:
      - 8080
    ports:
      - "8081:8080"
    networks:
      - nextcloud_web
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_URL: https://mercator.sourcentis.com

      DB_CONNECTION: mariadb
      DB_HOST: mercator-db
      DB_PORT: 3306
      DB_DATABASE: mercator
      DB_USERNAME: mercator
      DB_PASSWORD: MercatorPass123

      CACHE_DRIVER: file
      SESSION_DRIVER: file
    command: [ "wait-for-db.sh", "php-fpm" ]
    depends_on:
      mercator-db:
        condition: service_healthy

volumes:
  mercator_db_data:
  mercator_app_data:
